export const EVENT_TYPES = {
  USER_FOLLOWED: 'USER_FOLLOWED',
  POST_LIKED: 'POST_LIKED',
  COMMENT_CREATED: 'COMMENT_CREATED',
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  ORDER_STATUS_CHANGED: 'ORDER_STATUS_CHANGED',
  PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
  SECURITY_ALERT: 'SECURITY_ALERT',
};